"""add user table

Revision ID: f0454514b349
Revises: 282f2b6f8d4c
Create Date: 2024-07-12 20:02:45.589419

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import orm

from alembic import op
from src.auth.models import User
from src.core.security import get_password_hash

# revision identifiers, used by Alembic.
revision: str = "f0454514b349"
down_revision: Union[str, None] = "282f2b6f8d4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False, comment="id"),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("fullname", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("create_date", sa.DateTime(), server_default=sa.text("now()"), nullable=False, comment="created_at"),
        sa.Column("update_date", sa.DateTime(), nullable=True, comment="updated_at"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    # ### end Alembic commands ###

    user = User()
    user.email = "admin@mail.ru"
    user.fullname = "admin"
    user.is_superuser = True
    user.hashed_password = get_password_hash("admin")

    session.add(user)
    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
