"""Initial tables

Revision ID: 282f2b6f8d4c
Revises: 
Create Date: 2024-07-10 19:28:53.520861

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "282f2b6f8d4c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    table = op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="id"),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("delete_date", sa.DateTime(), nullable=True, comment="deleted_at"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=True)

    op.bulk_insert(
        table,
        [
            {"name": "Test project"},
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
